stages:
  - test
  - build
  - security

include:
  - local: .ci/test.yml
  - local: .ci/build.yml

trivy_scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL .