stages:
  - test
  - build

run-tests:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Тесты creature service"
    - python -m pytest test/unit/service/test_creature.py -v
    - echo "Тесты data layer creature"
    - python -m pytest test/unit/data/creature.py -v
  only:
    - merge_requests
    - master

build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Сборка Docker образа"
    - docker build -t fastapi-app:$CI_COMMIT_SHORT_SHA .
    - echo "Образ собран"
  only:
    - master