stages:
  - test
  - build

variables:
  DOCKER_TLS_CERTDIR: ""  # отключаем TLS для docker-in-docker

# ======================
# TEST STAGE
# ======================
run-tests:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose -f docker-compose.ci.yml version
  script:
    - echo "Поднимаем базу..."
    - docker-compose -f docker-compose.ci.yml up -d db
    - echo "Применяем миграции..."
    - docker-compose -f docker-compose.ci.yml run --rm migrate
    - echo "Запускаем интеграционные тесты..."
    - docker-compose -f docker-compose.ci.yml run --rm web pytest test/integration/database/test_postgresql_integration.py -v
  after_script:
    - echo "Останавливаем и удаляем контейнеры..."
    - docker-compose -f docker-compose.ci.yml down -v
  only:
    - merge_requests
    - master

# ======================
# BUILD STAGE
# ======================
build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Сборка Docker образа"
    - docker build -t fastapi-app:$CI_COMMIT_SHORT_SHA .
    - echo "Образ собран"
  rules:
    - if: '$CI_COMMIT_BRANCH' 
