# alembic.ini

[alembic]
# path to migration scripts.
script_location = %(here)s/alembic

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

path_separator = os

# ВАЖНО: ИСПРАВЬТЕ ЭТУ СТРОКУ!
sqlalchemy.url = postgresql+psycopg://postgres:postgres@db:5432/app


[post_write_hooks]
# можно раскомментировать black для автоформатирования
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 88 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S