# docker-compose.dev.yml
#version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: video-db-dev
    environment:
      POSTGRES_DB: video_platform
      POSTGRES_USER: video
      POSTGRES_PASSWORD: video123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U video"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Пока без миграций в Docker - делаем локально
  # web тоже запускаем локально для отладки

volumes:
  postgres_data: