version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Единственная точка выполнения миграций
  migrate:
    build: .
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        alembic upgrade head
      "
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/app
    volumes:
      - ./src:/app/src
      - ./db:/app/db
      - ./model:/app/model
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini

  web:
    build: .
    command: >
      sh -c "
        echo 'Starting API...' &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-config /app/logging.ini --access-log
      "
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/app
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/

      DELIVERY_MODE: ${DELIVERY_MODE:-local}
      DELIVERY_BASE_URL: ${DELIVERY_BASE_URL:-http://origin}
      DELIVERY_PUBLIC_BASE_URL: ${DELIVERY_PUBLIC_BASE_URL:-http://localhost:8080}

      REDIS_URL: redis://redis:6379/0
      VIDEO_LOCK_TTL_SECONDS: "3600"

      HLS_TOKEN_SECRET: ${HLS_TOKEN_SECRET:-super-long-random-secret-1234567890}
      HLS_TOKEN_TTL_SECONDS: ${HLS_TOKEN_TTL_SECONDS:-300}

    volumes:
      - ./src:/app/src
      - ./web:/app/web
      - ./service:/app/service
      - ./db:/app/db
      - ./model:/app/model
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - uploads_data:/app/uploads

  worker:
    build: .
    command: python -m src.worker
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/app
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379/0
      VIDEO_LOCK_TTL_SECONDS: "3600"
    volumes:
      - ./logging.ini:/app/logging.ini
      - ./src:/app/src
      - ./service:/app/service
      - ./db:/app/db
      - ./model:/app/model
      - uploads_data:/app/uploads

  outbox:
    build: .
    command: python -m src.outbox_publisher
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/app
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      OUTBOX_BATCH_SIZE: "50"
      OUTBOX_POLL_INTERVAL: "0.5"
    volumes:
      - ./src:/app/src
      - ./service:/app/service
      - ./db:/app/db
      - ./model:/app/model

  origin:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads_data:/app/uploads
    depends_on:
      web:
        condition: service_started

volumes:
  postgres_data:
  uploads_data: