apiVersion: v1
kind: ConfigMap
metadata:
  name: video-platform-config
  namespace: {{ .Values.global.namespace }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}

  PUBLIC_BASE_URL: {{ .Values.global.publicBaseUrl | quote }}
  MEDIA_BASE_URL: {{ .Values.global.mediaBaseUrl | quote }}

  DELIVERY_MODE: {{ .Values.app.deliveryMode | quote }}
  DELIVERY_BASE_URL: {{ .Values.app.deliveryBaseUrl | quote }}
  DELIVERY_PUBLIC_BASE_URL: {{ .Values.global.mediaBaseUrl | quote }}

  HLS_PUBLIC_BASE_URL: {{ .Values.global.mediaBaseUrl | quote }}
  HLS_PUBLIC_PATH_PREFIX: {{ .Values.app.hlsPublicPathPrefix | quote }}

  storage_type: {{ .Values.app.storageType | quote }}
  storage_path: {{ .Values.app.storagePath | quote }}
  STORAGE_PATH: {{ .Values.app.storagePath | quote }}

  ORIGIN_BASE_URL: {{ .Values.global.mediaBaseUrl | quote }}

  REDIS_URL: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
  VIDEO_LOCK_TTL_SECONDS: "3600"

  RABBIT_QUEUE: "video.process"
  RABBIT_EVENTS_EXCHANGE: "video.events.x"
  RABBIT_EVENTS_QUEUE: "events.q"
  RABBIT_EVENTS_ROUTING_KEY: "video.events"

  access_token_expire_minutes: {{ .Values.app.accessTokenExpireMinutes | quote }}