apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-proxy-headers
  namespace: video-platform
data:
  Host: "video-platform.local"
  X-Forwarded-Host: "video-platform.local"
  X-Forwarded-Proto: "http"
  X-Forwarded-Port: "80"