apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: {{ .Values.global.namespace }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: migrate
    spec:
      restartPolicy: Never

      imagePullSecrets:
        - name: gitlab-registry-secret

      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for postgres..."
              until nc -z {{ .Values.postgres.host }} {{ .Values.postgres.port }}; do
                sleep 2
              done
              echo "Postgres is ready"

      containers:
        - name: migrate
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Running migrations..." &&
              alembic upgrade head
          envFrom:
            - configMapRef:
                name: video-platform-config
            - secretRef:
                name: {{ .Values.secrets.appSecretName }}