apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-platform-monitoring
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .Values.global.domain }}"
    nginx.ingress.kubernetes.io/proxy-set-headers: "{{ .Values.global.namespace }}/grafana-proxy-headers"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000

          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090