{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.appSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  secret_key: {{ .Values.secrets.jwtSecret | quote }}
  database_write_url: "postgresql+psycopg://{{ .Values.postgres.user }}:{{ .Values.secrets.postgresPassword }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}"
  database_read_url: "postgresql+psycopg://{{ .Values.postgres.user }}:{{ .Values.secrets.postgresPassword }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}"
  RABBIT_URL: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.secrets.rabbitmqPassword }}@{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}/"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgresSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRESQL_POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRESQL_USERNAME: {{ .Values.postgres.user | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRESQL_DATABASE: {{ .Values.postgres.db | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmqSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmqPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.grafanaSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
{{- end }}