{{- if eq .Values.app.storageType "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}
{{- end }}