apiVersion: v1
kind: Service
metadata:
  name: video-events-consumer
  namespace: video-platform
spec:
  type: ClusterIP
  selector:
    app: video-events-consumer
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-events-consumer
  namespace: video-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-events-consumer
  template:
    metadata:
      labels:
        app: video-events-consumer
    spec:
      containers:
        - name: video-events-consumer
          image: {{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          command:
            - python
            - -m
            - src.video_events_consumer
          env:
            - name: SERVICE_NAME
              value: video-events-consumer
            - name: METRICS_PORT
              value: "9100"
            - name: database_write_url
              value: postgresql+psycopg://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres-master:5432/{{ .Values.postgres.db }}
            - name: database_read_url
              value: postgresql+psycopg://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres-master:5432/{{ .Values.postgres.db }}
            - name: RABBIT_URL
              value: amqp://{{ .Values.rabbitmq.user }}:{{ .Values.rabbitmq.password }}@rabbitmq:5672/
          ports:
            - containerPort: 9100
              name: metrics