apiVersion: v1
kind: Service
metadata:
  name: video-events-consumer
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: video-events-consumer
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-events-consumer
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-events-consumer
  template:
    metadata:
      labels:
        app: video-events-consumer
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret

      containers:
        - name: video-events-consumer
          image: {{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          command:
            - python
            - -m
            - src.video_events_consumer
          envFrom:
            - configMapRef:
                name: video-platform-config
            - secretRef:
                name: {{ .Values.secrets.appSecretName }}
          env:
            - name: SERVICE_NAME
              value: video-events-consumer
            - name: METRICS_PORT
              value: "9100"
          ports:
            - containerPort: 9100
              name: metrics