apiVersion: v1
kind: Service
metadata:
  name: video-api
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: video-api
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret

      containers:
        - name: video-api
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              uvicorn src.video_api_main:app --host 0.0.0.0 --port 8000 --log-config /app/logging.ini --access-log
          envFrom:
            - configMapRef:
                name: video-platform-config
            - secretRef:
                name: {{ .Values.secrets.appSecretName }}
          env:
            - name: SERVICE_NAME
              value: video-api
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20