apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: learning-app-backend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          command:
            - /bin/sh
            - -c
            - |
              echo "Starting web..." &&
              uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-config /app/logging.ini --access-log

          env:
            - name: SERVICE_NAME
              value: web

            - name: database_write_url
              value: postgresql+psycopg://postgres:postgres@postgres:5432/app

            - name: database_read_url
              value: postgresql+psycopg://postgres:postgres@postgres:5432/app

            - name: RABBIT_URL
              value: amqp://guest:guest@rabbitmq:5672/

            - name: REDIS_URL
              value: redis://redis:6379/0

            - name: PUBLIC_HOST
              value: "127.0.0.1"

            - name: PUBLIC_HTTP_PORT
              value: "8080"

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc