"""add error_message to videos

Revision ID: 90d22c3ea9c6
Revises: xxx
Create Date: 2026-02-09 08:52:57.796517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d22c3ea9c6'
down_revision: Union[str, Sequence[str], None] = 'xxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='taskstatus'),
               nullable=False)
    op.alter_column('processing_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_processing_tasks_id', table_name='processing_tasks')
    op.drop_constraint('processing_tasks_celery_task_id_key', 'processing_tasks', type_='unique')
    op.create_index(op.f('ix_processing_tasks_celery_task_id'), 'processing_tasks', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_processing_tasks_created_at'), 'processing_tasks', ['created_at'], unique=False)
    op.create_index('ix_processing_tasks_video_status', 'processing_tasks', ['video_id', 'status'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'storage_limit',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'used_storage',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    op.alter_column('video_formats', 'resolution',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('video_formats', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_formats', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_formats', 'codec',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('video_formats', 'bitrate_kbps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_formats', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('video_formats', 'is_ready',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('video_formats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_video_formats_id', table_name='video_formats')
    op.add_column('videos', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.alter_column('videos', 'status',
               existing_type=postgresql.ENUM('UPLOADING', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='videostatus'),
               nullable=False)
    op.alter_column('videos', 'visibility',
               existing_type=postgresql.ENUM('PUBLIC', 'PRIVATE', 'UNLISTED', name='visibility'),
               nullable=False)
    op.alter_column('videos', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('videos', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('videos', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_videos_owner_status', 'videos', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_videos_share_token'), 'videos', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_share_token'), table_name='videos')
    op.drop_index('ix_videos_owner_status', table_name='videos')
    op.alter_column('videos', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('videos', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('videos', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('videos', 'visibility',
               existing_type=postgresql.ENUM('PUBLIC', 'PRIVATE', 'UNLISTED', name='visibility'),
               nullable=True)
    op.alter_column('videos', 'status',
               existing_type=postgresql.ENUM('UPLOADING', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='videostatus'),
               nullable=True)
    op.drop_column('videos', 'share_token')
    op.drop_column('videos', 'error_message')
    op.create_index('ix_video_formats_id', 'video_formats', ['id'], unique=False)
    op.alter_column('video_formats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_formats', 'is_ready',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('video_formats', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('video_formats', 'bitrate_kbps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_formats', 'codec',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('video_formats', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_formats', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_formats', 'resolution',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'used_storage',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'storage_limit',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_processing_tasks_video_status', table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_created_at'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_celery_task_id'), table_name='processing_tasks')
    op.create_unique_constraint('processing_tasks_celery_task_id_key', 'processing_tasks', ['celery_task_id'])
    op.create_index('ix_processing_tasks_id', 'processing_tasks', ['id'], unique=False)
    op.alter_column('processing_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='taskstatus'),
               nullable=True)
    op.alter_column('processing_tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
