apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-platform-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8000

          - path: /api/v1/videos
            pathType: Prefix
            backend:
              service:
                name: video-api
                port:
                  number: 8000

          - path: /api/v1/uploads
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: 8000

          - path: /api/v1/live
            pathType: Prefix
            backend:
              service:
                name: live-api
                port:
                  number: 8000

          - path: /live/sessions
            pathType: Prefix
            backend:
              service:
                name: live-api
                port:
                  number: 8000

          - path: /origin/live
            pathType: Prefix
            backend:
              service:
                name: origin
                port:
                  number: 80

          - path: /origin/hls
            pathType: Prefix
            backend:
              service:
                name: origin
                port:
                  number: 80

          - path: /origin/thumb
            pathType: Prefix
            backend:
              service:
                name: origin
                port:
                  number: 80

          - path: /live
            pathType: Prefix
            backend:
              service:
                name: origin
                port:
                  number: 80

          - path: /hls
            pathType: Prefix
            backend:
              service:
                name: origin
                port:
                  number: 80

          - path: /thumb
            pathType: Prefix
            backend:
              service:
                name: origin
                port:
                  number: 80

          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8000

          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8000

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3001