worker_processes  1;

error_log /var/log/nginx/error.log info;

events { worker_connections  1024; }

rtmp {
  server {
    listen 1935;
    chunk_size 4096;

    application live {
      live on;
      record off;

      # НЕ ждать видео/ключевой кадр: пусть exec_publish стартует сразу,
      # а устойчивость обеспечиваем ретраями/ожиданием в on_publish.sh
      # wait_video on;
      # wait_key on;

      exec_publish      /opt/scripts/on_publish.sh $name;
      exec_publish_done /opt/scripts/on_publish_done.sh $name;
    }
  }
}

http {
  server {
    listen 8081;
    location /healthz { return 200 "ok\n"; }
  }
}